import { describe, it, expect, beforeEach, beforeAll, afterAll } from "vitest";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readlinkSync,
  rmSync,
  writeFileSync,
  lstatSync,
} from "fs";
import { join } from "path";
import { tmpdir } from "os";
import Database from "better-sqlite3";
import { createTestDb } from "../helpers.js";
import { setDb, type FlockctlDb } from "../../db/index.js";
import { projects, workspaces } from "../../db/schema.js";
import {
  loadProjectAgentsSource,
  loadWorkspaceAgentsSource,
  loadProjectAgentsEffective,
  loadWorkspaceAgentsEffective,
  saveProjectAgentsSource,
  saveWorkspaceAgentsSource,
  reconcileAgentsForProject,
  reconcileAgentsForWorkspace,
  reconcileAllProjectsInWorkspaceAgents,
  reconcileAllAgents,
  mergeAgents,
  buildWorkspaceRootAgents,
} from "../../services/claude-agents-sync.js";
import { symlinkSync, unlinkSync } from "fs";

let db: FlockctlDb;
let sqlite: Database.Database;
let tmpBase: string;

beforeAll(() => {
  const t = createTestDb();
  db = t.db;
  sqlite = t.sqlite;
  setDb(db, sqlite);
  tmpBase = join(tmpdir(), `flockctl-agents-sync-${process.pid}`);
  mkdirSync(tmpBase, { recursive: true });
});

afterAll(() => {
  sqlite.close();
  try { rmSync(tmpBase, { recursive: true, force: true }); } catch {}
});

beforeEach(() => {
  // Clean DB and tmp between tests so workspace/project IDs and paths don't collide.
  sqlite.exec(`DELETE FROM projects; DELETE FROM workspaces;`);
  try { rmSync(tmpBase, { recursive: true, force: true }); } catch {}
  mkdirSync(tmpBase, { recursive: true });
});

function makeWorkspace(name: string): { id: number; path: string } {
  const wsPath = join(tmpBase, name);
  mkdirSync(wsPath, { recursive: true });
  const ws = db.insert(workspaces).values({ name, path: wsPath }).returning().get()!;
  return { id: ws.id, path: wsPath };
}

function makeProject(name: string, opts: { workspaceId?: number; parentDir?: string } = {}): { id: number; path: string } {
  const projPath = join(opts.parentDir ?? tmpBase, name);
  mkdirSync(projPath, { recursive: true });
  const p = db.insert(projects).values({ name, path: projPath, workspaceId: opts.workspaceId ?? null }).returning().get()!;
  return { id: p.id, path: projPath };
}

describe("mergeAgents", () => {
  it("returns empty string when both inputs are empty", () => {
    expect(mergeAgents("", "")).toBe("");
    expect(mergeAgents("   ", "\n\n")).toBe("");
  });

  it("prepends auto-generated header and wraps project-only content in a BEGIN/END block", () => {
    const out = mergeAgents("", "# Project rules");
    expect(out).toContain("AUTO-GENERATED by swarmctl");
    expect(out).toContain(".flockctl/AGENTS.md");
    expect(out).toContain("<!-- BEGIN project AGENTS.md");
    expect(out).toContain("<!-- END project AGENTS.md");
    expect(out).toContain("# Project rules");
    expect(out).not.toContain("BEGIN workspace AGENTS.md");
    expect(out.endsWith("\n")).toBe(true);
  });

  it("prepends auto-generated header and wraps workspace-only content in a BEGIN/END block", () => {
    const out = mergeAgents("# Workspace rules", "");
    expect(out).toContain("AUTO-GENERATED by swarmctl");
    expect(out).toContain("<!-- BEGIN workspace AGENTS.md");
    expect(out).toContain("<!-- END workspace AGENTS.md");
    expect(out).toContain("# Workspace rules");
    expect(out).not.toContain("BEGIN project AGENTS.md");
    expect(out.endsWith("\n")).toBe(true);
  });

  it("wraps both blocks with BEGIN/END markers when both non-empty, with header prepended", () => {
    const out = mergeAgents("# WS", "# PR");
    expect(out).toContain("AUTO-GENERATED by swarmctl");
    expect(out).toContain("<!-- BEGIN workspace AGENTS.md");
    expect(out).toContain("<!-- END workspace AGENTS.md");
    expect(out).toContain("<!-- BEGIN project AGENTS.md");
    expect(out).toContain("<!-- END project AGENTS.md");
    expect(out).toContain("# WS");
    expect(out).toContain("# PR");
    expect(out.endsWith("\n")).toBe(true);
  });

  it("is byte-stable for identical inputs", () => {
    const a = mergeAgents("foo", "bar");
    const b = mergeAgents("foo", "bar");
    expect(a).toBe(b);
  });
});

describe("buildWorkspaceRootAgents", () => {
  it("returns empty string for empty source", () => {
    expect(buildWorkspaceRootAgents("")).toBe("");
    expect(buildWorkspaceRootAgents("   \n")).toBe("");
  });

  it("prepends auto-generated header for non-empty source", () => {
    const out = buildWorkspaceRootAgents("# Workspace rules");
    expect(out).toContain("AUTO-GENERATED by swarmctl");
    expect(out).toContain(".flockctl/AGENTS.md  in this workspace");
    expect(out).toContain("# Workspace rules");
    expect(out.endsWith("\n")).toBe(true);
  });
});

describe("source IO", () => {
  it("save/load roundtrip for project source", () => {
    const { path } = makeProject("io-proj");
    saveProjectAgentsSource(path, "hello world");
    expect(loadProjectAgentsSource(path)).toBe("hello world");
    expect(existsSync(join(path, ".flockctl", "AGENTS.md"))).toBe(true);
  });

  it("save/load roundtrip for workspace source", () => {
    const { path } = makeWorkspace("io-ws");
    saveWorkspaceAgentsSource(path, "ws content");
    expect(loadWorkspaceAgentsSource(path)).toBe("ws content");
  });

  it("returns empty string when source file doesn't exist", () => {
    const { path } = makeProject("no-src");
    expect(loadProjectAgentsSource(path)).toBe("");
  });
});

describe("reconcileAgentsForProject", () => {
  it("writes merged AGENTS.md and CLAUDE.md symlink at project root", () => {
    const ws = makeWorkspace("ws-1");
    const proj = makeProject("p-1", { workspaceId: ws.id, parentDir: ws.path });
    saveWorkspaceAgentsSource(ws.path, "# Workspace rules");
    saveProjectAgentsSource(proj.path, "# Project rules");

    reconcileAgentsForProject(proj.id);

    const rootAgents = readFileSync(join(proj.path, "AGENTS.md"), "utf-8");
    expect(rootAgents).toContain("# Workspace rules");
    expect(rootAgents).toContain("# Project rules");

    const linkPath = join(proj.path, "CLAUDE.md");
    const lst = lstatSync(linkPath);
    expect(lst.isSymbolicLink()).toBe(true);
    expect(readlinkSync(linkPath)).toBe("AGENTS.md");
  });

  it("writes only project content when workspace source is empty", () => {
    const ws = makeWorkspace("ws-empty");
    const proj = makeProject("p-empty", { workspaceId: ws.id, parentDir: ws.path });
    saveProjectAgentsSource(proj.path, "# Just project");

    reconcileAgentsForProject(proj.id);

    const rootAgents = readFileSync(join(proj.path, "AGENTS.md"), "utf-8");
    expect(rootAgents).toContain("AUTO-GENERATED by swarmctl");
    expect(rootAgents).toContain("# Just project");
    expect(rootAgents).not.toContain("BEGIN workspace");
  });

  it("removes root AGENTS.md and symlink when both sources are empty", () => {
    const proj = makeProject("p-clear");
    // First populate, reconcile, then clear and reconcile again.
    saveProjectAgentsSource(proj.path, "x");
    reconcileAgentsForProject(proj.id);
    expect(existsSync(join(proj.path, "AGENTS.md"))).toBe(true);

    saveProjectAgentsSource(proj.path, "");
    reconcileAgentsForProject(proj.id);
    expect(existsSync(join(proj.path, "AGENTS.md"))).toBe(false);
    expect(lstatSyncSafe(join(proj.path, "CLAUDE.md"))?.isSymbolicLink()).toBeFalsy();
  });

  it("is byte-stable: second reconcile with same inputs leaves mtime unchanged", () => {
    const proj = makeProject("p-stable");
    saveProjectAgentsSource(proj.path, "stable content");
    reconcileAgentsForProject(proj.id);
    const path1 = join(proj.path, "AGENTS.md");
    const mtime1 = lstatSync(path1).mtimeMs;

    // Sleep would be flaky; instead rely on writeAtomic short-circuit.
    reconcileAgentsForProject(proj.id);
    const mtime2 = lstatSync(path1).mtimeMs;
    expect(mtime2).toBe(mtime1);
  });

  it("leaves a regular CLAUDE.md file untouched and warns", () => {
    const proj = makeProject("p-clash");
    saveProjectAgentsSource(proj.path, "stuff");
    // Pre-existing CLAUDE.md as a regular file should NOT be overwritten.
    writeFileSync(join(proj.path, "CLAUDE.md"), "user wrote this manually");

    reconcileAgentsForProject(proj.id);

    const linkPath = join(proj.path, "CLAUDE.md");
    const lst = lstatSync(linkPath);
    expect(lst.isSymbolicLink()).toBe(false);
    expect(readFileSync(linkPath, "utf-8")).toBe("user wrote this manually");
  });
});

describe("reconcileAgentsForWorkspace", () => {
  it("writes workspace source to workspace root AGENTS.md and symlinks CLAUDE.md", () => {
    const ws = makeWorkspace("ws-write");
    saveWorkspaceAgentsSource(ws.path, "workspace stuff");
    reconcileAgentsForWorkspace(ws.id);

    const wsAgents = readFileSync(join(ws.path, "AGENTS.md"), "utf-8");
    expect(wsAgents).toContain("AUTO-GENERATED by swarmctl");
    expect(wsAgents).toContain("workspace stuff");
    expect(lstatSync(join(ws.path, "CLAUDE.md")).isSymbolicLink()).toBe(true);
  });
});

describe("reconcileAllProjectsInWorkspaceAgents (cascade)", () => {
  it("re-reconciles every child project so workspace edits propagate", () => {
    const ws = makeWorkspace("ws-cascade");
    const a = makeProject("p-a", { workspaceId: ws.id, parentDir: ws.path });
    const b = makeProject("p-b", { workspaceId: ws.id, parentDir: ws.path });
    saveProjectAgentsSource(a.path, "# A");
    saveProjectAgentsSource(b.path, "# B");

    // Initial state: no workspace content.
    reconcileAgentsForProject(a.id);
    reconcileAgentsForProject(b.id);
    expect(loadProjectAgentsEffective(a.path)).toContain("# A");
    expect(loadProjectAgentsEffective(b.path)).toContain("# B");

    // Edit workspace source and cascade.
    saveWorkspaceAgentsSource(ws.path, "# WS rules");
    reconcileAllProjectsInWorkspaceAgents(ws.id);

    expect(loadWorkspaceAgentsEffective(ws.path)).toContain("# WS rules");
    expect(loadProjectAgentsEffective(a.path)).toContain("# WS rules");
    expect(loadProjectAgentsEffective(a.path)).toContain("# A");
    expect(loadProjectAgentsEffective(b.path)).toContain("# WS rules");
    expect(loadProjectAgentsEffective(b.path)).toContain("# B");
  });
});

describe("reconcile edge cases", () => {
  it("reconcileAgentsForProject no-ops when project id doesn't exist", () => {
    expect(() => reconcileAgentsForProject(999999)).not.toThrow();
  });

  it("reconcileAgentsForProject no-ops when project.path is missing on disk", () => {
    const fakePath = join(tmpBase, "ghost");
    const p = db.insert(projects).values({ name: "ghost", path: fakePath }).returning().get()!;
    expect(() => reconcileAgentsForProject(p.id)).not.toThrow();
    expect(existsSync(join(fakePath, "AGENTS.md"))).toBe(false);
  });

  it("reconcileAgentsForProject skips workspace source when workspace path missing", () => {
    const ghostWsPath = join(tmpBase, "missing-ws");
    const ws = db.insert(workspaces).values({ name: "gws", path: ghostWsPath }).returning().get()!;
    const proj = makeProject("p-ghostws", { workspaceId: ws.id });
    saveProjectAgentsSource(proj.path, "# Just proj");
    reconcileAgentsForProject(proj.id);
    expect(readFileSync(join(proj.path, "AGENTS.md"), "utf-8")).toContain("# Just proj");
  });

  it("reconcileAgentsForWorkspace no-ops when ws id doesn't exist", () => {
    expect(() => reconcileAgentsForWorkspace(999999)).not.toThrow();
  });

  it("reconcileAgentsForWorkspace no-ops when ws.path missing on disk", () => {
    const fakePath = join(tmpBase, "ghost-ws");
    const ws = db.insert(workspaces).values({ name: "g", path: fakePath }).returning().get()!;
    expect(() => reconcileAgentsForWorkspace(ws.id)).not.toThrow();
  });

  it("existing symlink pointing to correct target is preserved (no rewrite)", () => {
    const proj = makeProject("p-keeplink");
    saveProjectAgentsSource(proj.path, "x");
    reconcileAgentsForProject(proj.id);
    const linkPath = join(proj.path, "CLAUDE.md");
    expect(readlinkSync(linkPath)).toBe("AGENTS.md");

    reconcileAgentsForProject(proj.id);
    expect(readlinkSync(linkPath)).toBe("AGENTS.md");
  });

  it("existing symlink pointing to wrong target is replaced", () => {
    const proj = makeProject("p-wronglink");
    saveProjectAgentsSource(proj.path, "x");
    // Put a symlink at CLAUDE.md pointing somewhere else first.
    const linkPath = join(proj.path, "CLAUDE.md");
    symlinkSync("SOMEWHERE_ELSE.md", linkPath);

    reconcileAgentsForProject(proj.id);
    expect(readlinkSync(linkPath)).toBe("AGENTS.md");
  });

  it("reconcileAllAgents reconciles every workspace and project", () => {
    const ws1 = makeWorkspace("all-ws-1");
    const ws2 = makeWorkspace("all-ws-2");
    saveWorkspaceAgentsSource(ws1.path, "ws1");
    saveWorkspaceAgentsSource(ws2.path, "ws2");
    const p1 = makeProject("all-p-1", { workspaceId: ws1.id, parentDir: ws1.path });
    saveProjectAgentsSource(p1.path, "p1");

    reconcileAllAgents();

    expect(readFileSync(join(ws1.path, "AGENTS.md"), "utf-8")).toContain("ws1");
    expect(readFileSync(join(ws2.path, "AGENTS.md"), "utf-8")).toContain("ws2");
    expect(readFileSync(join(p1.path, "AGENTS.md"), "utf-8")).toContain("ws1");
    expect(readFileSync(join(p1.path, "AGENTS.md"), "utf-8")).toContain("p1");
  });

  it("reconcileAllAgents swallows per-workspace and per-project errors", () => {
    // Workspace whose path is removed between insert and reconcile triggers the
    // early-return branch, not the catch. Force a catch by inserting rows then
    // removing their on-disk dirs *after* successful insert — the code will hit
    // existsSync check and return cleanly. So we validate via no-throw.
    const ws = makeWorkspace("err-ws");
    const proj = makeProject("err-p", { workspaceId: ws.id, parentDir: ws.path });
    saveWorkspaceAgentsSource(ws.path, "x");
    saveProjectAgentsSource(proj.path, "y");
    rmSync(ws.path, { recursive: true, force: true });

    expect(() => reconcileAllAgents()).not.toThrow();
  });
});

describe("symlink handling variants", () => {
  it("removes stale symlink when sources become empty", () => {
    const proj = makeProject("p-stale-link");
    saveProjectAgentsSource(proj.path, "content");
    reconcileAgentsForProject(proj.id);
    const linkPath = join(proj.path, "CLAUDE.md");
    expect(existsSync(linkPath)).toBe(true);

    saveProjectAgentsSource(proj.path, "");
    reconcileAgentsForProject(proj.id);
    // Symlink should have been removed along with root AGENTS.md.
    expect(lstatSyncSafe(linkPath)?.isSymbolicLink()).toBeFalsy();
  });

  it("leaves regular CLAUDE.md alone even when both sources become empty", () => {
    const proj = makeProject("p-regular-file");
    saveProjectAgentsSource(proj.path, "stuff");
    writeFileSync(join(proj.path, "CLAUDE.md"), "hand-written");

    saveProjectAgentsSource(proj.path, "");
    reconcileAgentsForProject(proj.id);
    expect(readFileSync(join(proj.path, "CLAUDE.md"), "utf-8")).toBe("hand-written");
  });
});

function lstatSyncSafe(path: string) {
  try {
    return lstatSync(path);
  } catch {
    return null;
  }
}
