import { describe, it, expect } from "vitest";
import { generateTestsFromSM } from "../../services/state-machines/sm-test-generator.js";
import type { StateMachine } from "../../services/state-machines/sm-parser.js";

const simpleSm: StateMachine = {
  states: ["idle", "running", "done"],
  initial: "idle",
  transitions: [
    { from: "idle", to: "running", event: "start" },
    { from: "running", to: "done", event: "finish" },
  ],
};

describe("generateTestsFromSM — header", () => {
  it("embeds the target path and import path in header comments", () => {
    const src = generateTestsFromSM(simpleSm, {
      targetPath: "/abs/out.test.ts",
      importFrom: "@/entities/order",
    });
    expect(src).toMatch(/\/\/ Auto-generated by sm-test-generator/);
    expect(src).toMatch(/\/\/ Target file: \/abs\/out\.test\.ts/);
    expect(src).toMatch(/\/\/ Entity import \(TODO\): @\/entities\/order/);
  });

  it("header is the first block (starts with //)", () => {
    const src = generateTestsFromSM(simpleSm, {
      targetPath: "x.test.ts",
      importFrom: "x",
    });
    expect(src.startsWith("// Auto-generated")).toBe(true);
  });
});

describe("generateTestsFromSM — preamble", () => {
  it("imports describe/it/expect from vitest", () => {
    const src = generateTestsFromSM(simpleSm, {
      targetPath: "x",
      importFrom: "x",
    });
    expect(src).toContain(
      `import { describe, it, expect } from "vitest";`,
    );
  });

  it("augments vitest's Assertion interface with placeholder matchers", () => {
    const src = generateTestsFromSM(simpleSm, {
      targetPath: "x",
      importFrom: "x",
    });
    expect(src).toContain(`declare module "vitest"`);
    expect(src).toMatch(/interface Assertion<T = any>/);
    expect(src).toContain("toTransitionFrom(state: string)");
    expect(src).toContain("toHoldInvariants(): void;");
    expect(src).toContain("interface AsymmetricMatchersContaining");
  });

  it("defines a notImplemented helper that throws", () => {
    const src = generateTestsFromSM(simpleSm, {
      targetPath: "x",
      importFrom: "x",
    });
    expect(src).toContain(
      `function notImplemented(message: string): never {`,
    );
    expect(src).toContain(
      "throw new Error(`SM harness not implemented: ${message}`);",
    );
  });
});

describe("generateTestsFromSM — transitions", () => {
  it("emits one it() per transition, uniquely indexed", () => {
    const src = generateTestsFromSM(simpleSm, {
      targetPath: "x",
      importFrom: "x",
    });
    expect(src).toContain(
      `it("[0] transitions from idle to running on start"`,
    );
    expect(src).toContain(
      `it("[1] transitions from running to done on finish"`,
    );
  });

  it("each it() wires the fluent matcher with the transition's fields", () => {
    const src = generateTestsFromSM(simpleSm, {
      targetPath: "x",
      importFrom: "x",
    });
    expect(src).toContain(
      `expect(sm).toTransitionFrom("idle").to("running").onEvent("start");`,
    );
    expect(src).toContain(
      `expect(sm).toTransitionFrom("running").to("done").onEvent("finish");`,
    );
  });

  it("emits it.todo when the state machine has zero transitions", () => {
    const emptySm: StateMachine = {
      states: ["only"],
      initial: "only",
      transitions: [],
    };
    const src = generateTestsFromSM(emptySm, {
      targetPath: "x",
      importFrom: "x",
    });
    expect(src).toContain(
      `it.todo("no transitions declared in state machine");`,
    );
    // and does NOT contain a real it( "[0] ..." entry
    expect(src).not.toMatch(/it\("\[0\] /);
  });

  it("safely escapes identifiers containing quotes and backslashes", () => {
    const trickySm: StateMachine = {
      states: ['weird"state', "plain"],
      initial: 'weird"state',
      transitions: [
        { from: 'weird"state', to: "plain", event: 'ev\\ent"x' },
      ],
    };
    const src = generateTestsFromSM(trickySm, {
      targetPath: "x",
      importFrom: "x",
    });
    // JSON.stringify escapes the inner quote and backslash.
    expect(src).toContain(`"weird\\"state"`);
    expect(src).toContain(`"ev\\\\ent\\"x"`);
  });

  it("embeds targetPath verbatim (not JSON-stringified) in header", () => {
    const src = generateTestsFromSM(simpleSm, {
      targetPath: "some path with spaces.ts",
      importFrom: "x",
    });
    expect(src).toContain("// Target file: some path with spaces.ts");
  });
});

describe("generateTestsFromSM — body structure", () => {
  it("wraps everything in a describe keyed by importFrom", () => {
    const src = generateTestsFromSM(simpleSm, {
      targetPath: "x",
      importFrom: "@/entities/order",
    });
    expect(src).toContain(
      `describe("state machine: @/entities/order"`,
    );
  });

  it("emits a transitions sub-describe and an invariants sub-describe", () => {
    const src = generateTestsFromSM(simpleSm, {
      targetPath: "x",
      importFrom: "x",
    });
    expect(src).toContain(`describe("transitions"`);
    expect(src).toContain(`describe("invariants"`);
    expect(src).toContain(
      `it("preserves state-machine invariants"`,
    );
    expect(src).toContain(`expect(sm).toHoldInvariants();`);
  });

  it("output ends with a trailing newline", () => {
    const src = generateTestsFromSM(simpleSm, {
      targetPath: "x",
      importFrom: "x",
    });
    expect(src.endsWith("\n")).toBe(true);
  });

  it("is a single string (header + preamble + body)", () => {
    const src = generateTestsFromSM(simpleSm, {
      targetPath: "x",
      importFrom: "x",
    });
    // sanity: indexOf ordering
    const headerIdx = src.indexOf("// Auto-generated");
    const preambleIdx = src.indexOf('import { describe');
    const bodyIdx = src.indexOf('describe("state machine');
    expect(headerIdx).toBeLessThan(preambleIdx);
    expect(preambleIdx).toBeLessThan(bodyIdx);
  });
});
