/**
 * Vitest harness emitter for state-machine specs.
 *
 * Consumes a parsed {@link StateMachine} and produces a TypeScript source
 * string that can be written to disk and executed by vitest. The emitted
 * file:
 *
 *   - imports `describe`, `it`, `expect` from `"vitest"`
 *   - augments vitest's `Assertion` interface with two placeholder matchers
 *     (`toTransitionFrom(...).to(...).onEvent(...)` and `toHoldInvariants()`)
 *     so the file typechecks under `tsc --noEmit` even though the matchers
 *     are not yet implemented
 *   - defines a local `notImplemented(message): never` helper that throws a
 *     clear error — so every generated test fails red the first time it
 *     runs, never green-by-accident
 *   - emits one `it()` per transition plus exactly one invariants block
 *
 * State, event and transition names are embedded via `JSON.stringify` so
 * arbitrary user-supplied identifiers (quotes, backslashes, unicode, line
 * breaks) stay syntactically valid inside the generated strings.
 */

import type { StateMachine } from "./sm-parser.js";

export interface GenerateTestsOptions {
  /**
   * Absolute or repo-relative path the generated file will be written to.
   * Embedded as a header comment for traceability — not used to resolve
   * imports inside the emitted source.
   */
  targetPath: string;
  /**
   * Module path the harness should ultimately import the entity under
   * test from. Recorded as a TODO comment so a human knows where to wire
   * the real state machine in once `notImplemented(...)` is replaced.
   */
  importFrom: string;
}

/** Safely embed a user-provided identifier as a TS string literal. */
function lit(value: string): string {
  return JSON.stringify(value);
}

/**
 * Generate a vitest harness source string from a parsed state machine.
 * The returned string is valid TypeScript and, when executed by vitest,
 * every generated `it()` fails with a "SM harness not implemented" error.
 */
export function generateTestsFromSM(
  sm: StateMachine,
  opts: GenerateTestsOptions,
): string {
  const notImplMessage = "SM harness: TODO wire in actual entity";

  const header = [
    `// Auto-generated by sm-test-generator — do not edit by hand.`,
    `// Target file: ${opts.targetPath}`,
    `// Entity import (TODO): ${opts.importFrom}`,
  ].join("\n");

  const preamble = [
    `import { describe, it, expect } from "vitest";`,
    ``,
    `// Placeholder matchers — the actual implementations will be provided`,
    `// by the SM harness once the entity under test is wired in. The module`,
    `// augmentation below only teaches TypeScript the shape; calling any of`,
    `// these at runtime will throw because \`notImplemented\` fires first.`,
    `declare module "vitest" {`,
    `  // eslint-disable-next-line @typescript-eslint/no-explicit-any`,
    `  interface Assertion<T = any> {`,
    `    toTransitionFrom(state: string): {`,
    `      to(state: string): { onEvent(event: string): void };`,
    `    };`,
    `    toHoldInvariants(): void;`,
    `  }`,
    `  interface AsymmetricMatchersContaining {`,
    `    toTransitionFrom(state: string): {`,
    `      to(state: string): { onEvent(event: string): void };`,
    `    };`,
    `    toHoldInvariants(): void;`,
    `  }`,
    `}`,
    ``,
    `function notImplemented(message: string): never {`,
    `  throw new Error(\`SM harness not implemented: \${message}\`);`,
    `}`,
  ].join("\n");

  const transitionIts = sm.transitions.map((t, i) => {
    // Titles go through JSON.stringify too — a transition name may include
    // quotes or backslashes and we don't want to break the `it(...)` call.
    const title = `transitions from ${t.from} to ${t.to} on ${t.event}`;
    const uniqueTitle = `[${i}] ${title}`;
    return [
      `    it(${lit(uniqueTitle)}, () => {`,
      `      const sm = notImplemented(${lit(notImplMessage)});`,
      `      expect(sm).toTransitionFrom(${lit(t.from)}).to(${lit(t.to)}).onEvent(${lit(t.event)});`,
      `    });`,
    ].join("\n");
  });

  const transitionsBlock =
    transitionIts.length > 0
      ? transitionIts.join("\n\n")
      : `    it.todo("no transitions declared in state machine");`;

  const body = [
    `describe(${lit(`state machine: ${opts.importFrom}`)}, () => {`,
    `  describe("transitions", () => {`,
    transitionsBlock,
    `  });`,
    ``,
    `  describe("invariants", () => {`,
    `    it("preserves state-machine invariants", () => {`,
    `      const sm = notImplemented(${lit(notImplMessage)});`,
    `      expect(sm).toHoldInvariants();`,
    `    });`,
    `  });`,
    `});`,
    ``,
  ].join("\n");

  return `${header}\n\n${preamble}\n\n${body}`;
}
