#!/usr/bin/env tsx
/**
 * CLI-Docker tier — `flockctl agents migrate` / `agents show`.
 *
 * Exercises the full Commander → planMigration → applyMigration → loader
 * chain against a real binary inside the disposable container. The unit
 * suites under src/__tests__/cli/agents-{show,migrate}.test.ts already
 * cover every branch of the underlying library; this tier's job is to
 * prove the shipped CLI resolves workspace relationships through the
 * daemon, writes to the right on-disk paths, and stays idempotent across
 * repeated invocations.
 *
 * Scenario (one container, sequential steps):
 *
 *   1. Seed an AI key so POST /workspaces + POST /projects succeed.
 *   2. Create a workspace + a project nested inside that workspace
 *      through the daemon REST API (same path the UI would take). The
 *      daemon's create handler provisions each side's `.flockctl/`
 *      scaffold and touches an empty `.flockctl/AGENTS.md`; it does NOT
 *      populate the root AGENTS.md.
 *   3. Overwrite `<project>/AGENTS.md` with a legacy auto-generated
 *      payload — the <!-- AUTO-GENERATED by flockctl ... --> header plus
 *      BEGIN/END workspace + project blocks — that the old reconciler
 *      used to emit. This is exactly the shape `planMigration` expects to
 *      split back into per-layer private sources.
 *   4. `flockctl agents migrate <project> --dry-run` → exit 0, stdout
 *      reports the plan (write + retire root + workspace-private write)
 *      and the dry-run banner, and the on-disk tree is byte-identical to
 *      its pre-invocation state (hash check).
 *   5. `flockctl agents migrate <project> --apply` → exit 0, "Applied."
 *      in stdout. Post-apply: root AGENTS.md is gone,
 *      `<project>/.flockctl/AGENTS.md` holds the project body, and
 *      `<workspace>/.flockctl/AGENTS.md` holds the workspace body (the
 *      daemon resolver walked projects→workspaceId→workspaces.path to
 *      find it — no flag needed from the CLI).
 *   6. Re-run `flockctl agents migrate <project> --apply` → exit 0. The
 *      plan now has nothing to do because the root file is already gone
 *      (`no AGENTS.md … nothing to migrate`), so stdout contains `noop`
 *      and does NOT contain `Applied.`.
 *   7. `flockctl agents show --effective <project>` → exit 0, stdout
 *      contains both the project body and the workspace body (the loader
 *      merged them transparently, and the `--effective` default renders
 *      the full string).
 *
 * Notes:
 *  - The runner in tests/cli-docker/run.ts globs `test-*.ts`, so the
 *    file has to live at this path (not `agents.test.ts`) to be picked
 *    up.
 *  - Printed plan format is owned by `printPlan` in
 *    src/services/claude/agents-migrate.ts — we match the actual tokens
 *    (`write:`, `noop:`, `delete:`) rather than the shorthand the brief
 *    used (`would write` / `would noop`), which never appears in the
 *    real output.
 *  - All assertions that inspect the filesystem run through the
 *    container via `ctx.exec(..., { raw: true })` so the check happens
 *    against the same mount the CLI wrote to.
 *
 * Verification:
 *   npm run test:cli-docker -- --grep agents
 */
import { createHash } from "node:crypto";
import { assert, withCliDocker, type CliDockerContext } from "./_harness.js";

const DAEMON_BOOT_TIMEOUT_MS = 30_000;

/**
 * The legacy reconciler output we need `planMigration` to split back up.
 * Mirrors the fixture shape used in src/__tests__/cli/agents-migrate.test.ts
 * but built inline here so the cli-docker tier stays self-contained — no
 * shared fixture file, no cross-tier imports.
 */
function legacyAgentsMd(workspaceBody: string, projectBody: string): string {
  return (
    "<!-- AUTO-GENERATED by flockctl — do not edit this file directly.\n" +
    "     CLAUDE.md in this directory is a symlink to this file. -->\n\n" +
    `<!-- BEGIN workspace AGENTS.md (from <workspace>/.flockctl/AGENTS.md) -->\n` +
    `${workspaceBody}\n` +
    `<!-- END workspace AGENTS.md -->\n\n` +
    `<!-- BEGIN project AGENTS.md (from <project>/.flockctl/AGENTS.md) -->\n` +
    `${projectBody}\n` +
    `<!-- END project AGENTS.md -->\n`
  );
}

/**
 * POST /keys → active AI key. `workspaces` + `projects` creation both
 * require a non-empty `allowedKeyIds` array (see parseRequiredAllowedKeyIds*
 * in src/routes/_allowed-keys.ts). claude_cli is cheapest to seed because it
 * has no keyValue requirement.
 */
async function seedAiKey(daemonUrl: string): Promise<number> {
  const res = await fetch(`${daemonUrl}/keys`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      provider: "claude_cli",
      providerType: "claude-agent-sdk",
      label: "agents-test-key",
      isActive: true,
    }),
  });
  const text = await res.text();
  assert(res.ok, `POST /keys failed: ${res.status} ${text}`);
  return (JSON.parse(text) as { id: number }).id;
}

interface WorkspaceRow {
  id: number;
  name: string;
  path: string;
}
interface ProjectRow {
  id: number;
  name: string;
  path: string;
  workspaceId: number | null;
}

async function createWorkspace(
  daemonUrl: string,
  name: string,
  keyId: number,
): Promise<WorkspaceRow> {
  const res = await fetch(`${daemonUrl}/workspaces`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ name, allowedKeyIds: [keyId] }),
  });
  const text = await res.text();
  assert(res.ok, `POST /workspaces failed: ${res.status} ${text}`);
  return JSON.parse(text) as WorkspaceRow;
}

async function createProject(
  daemonUrl: string,
  name: string,
  workspaceId: number,
  keyId: number,
): Promise<ProjectRow> {
  const res = await fetch(`${daemonUrl}/projects`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      name,
      workspaceId,
      allowedKeyIds: [keyId],
      importActions: [],
    }),
  });
  const text = await res.text();
  assert(res.ok, `POST /projects failed: ${res.status} ${text}`);
  return JSON.parse(text) as ProjectRow;
}

/**
 * Standalone project (no `workspaceId`) — lets `agents migrate` exercise
 * the `workspaceId === null` early return inside
 * `tryResolveWorkspacePathForProject`.
 */
async function createProjectStandalone(
  daemonUrl: string,
  name: string,
  keyId: number,
): Promise<ProjectRow> {
  const res = await fetch(`${daemonUrl}/projects`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      name,
      allowedKeyIds: [keyId],
      importActions: [],
    }),
  });
  const text = await res.text();
  assert(res.ok, `POST /projects (standalone) failed: ${res.status} ${text}`);
  return JSON.parse(text) as ProjectRow;
}

/**
 * Tree-hash helper. Used between the pre-dry-run snapshot and the post-
 * dry-run snapshot to prove `--dry-run` is side-effect-free on the actual
 * on-disk state the binary wrote (not just its announced plan).
 *
 * Runs inside the container so the hash sees the same mount as the CLI.
 * The node snippet walks the dir recursively and hashes a sorted list of
 * `<relpath>\0<kind>\0<payload>` records — matching the approach in the
 * unit-test suite (`hashTree` in agents-migrate.test.ts).
 */
async function treeHashInContainer(
  ctx: CliDockerContext,
  path: string,
): Promise<string> {
  const script = `
const fs = require("fs");
const path = require("path");
const { createHash } = require("crypto");
const root = ${JSON.stringify(path)};
const entries = [];
function walk(cur) {
  const items = fs.readdirSync(cur).sort();
  for (const name of items) {
    const full = path.join(cur, name);
    const rel = path.relative(root, full);
    const lst = fs.lstatSync(full);
    if (lst.isSymbolicLink()) {
      entries.push(rel + "\\0symlink\\0" + fs.readlinkSync(full));
    } else if (lst.isDirectory()) {
      entries.push(rel + "\\0dir\\0");
      walk(full);
    } else {
      entries.push(rel + "\\0file\\0" + fs.readFileSync(full, "utf-8"));
    }
  }
}
walk(root);
const h = createHash("sha256");
for (const e of entries) h.update(e).update("\\n");
process.stdout.write(h.digest("hex"));
`;
  const r = await ctx.exec(["node", "-e", script], {
    raw: true,
    timeoutMs: 10_000,
  });
  assert(r.code === 0, `treeHashInContainer failed: ${r.stderr || r.stdout}`);
  return r.stdout.trim();
}

/** Read a file inside the container. Returns null if absent. */
async function readFileInContainer(
  ctx: CliDockerContext,
  path: string,
): Promise<string | null> {
  const script = `
const fs = require("fs");
try {
  process.stdout.write(fs.readFileSync(${JSON.stringify(path)}, "utf-8"));
} catch (err) {
  if (err.code === "ENOENT") {
    process.stderr.write("__MISSING__");
    process.exit(2);
  }
  throw err;
}
`;
  const r = await ctx.exec(["node", "-e", script], {
    raw: true,
    timeoutMs: 5_000,
  });
  if (r.code === 2) return null;
  assert(r.code === 0, `readFileInContainer failed: ${r.stderr || r.stdout}`);
  return r.stdout;
}

/** Write a file into the container (UTF-8). Creates parent dirs as needed. */
async function writeFileInContainer(
  ctx: CliDockerContext,
  path: string,
  content: string,
): Promise<void> {
  // Pass the body through stdin so we don't have to escape arbitrary
  // markdown for the shell.
  const script = `
const fs = require("fs");
const path = require("path");
const out = ${JSON.stringify(path)};
fs.mkdirSync(path.dirname(out), { recursive: true });
let buf = "";
process.stdin.on("data", (d) => { buf += d.toString(); });
process.stdin.on("end", () => {
  fs.writeFileSync(out, buf, "utf-8");
});
`;
  const r = await ctx.exec(["node", "-e", script], {
    raw: true,
    timeoutMs: 5_000,
    stdin: content,
  });
  assert(r.code === 0, `writeFileInContainer failed: ${r.stderr || r.stdout}`);
}

async function pathExists(ctx: CliDockerContext, path: string): Promise<boolean> {
  const r = await ctx.exec(
    ["sh", "-c", `test -e ${JSON.stringify(path)} && echo yes || echo no`],
    { raw: true, timeoutMs: 5_000 },
  );
  return r.stdout.trim() === "yes";
}

await withCliDocker(async (ctx) => {
  // ── Boot the daemon ────────────────────────────────────────────────────
  const start = await ctx.exec(
    ["start", "--host", "0.0.0.0", "--allow-insecure-public"],
    { timeoutMs: DAEMON_BOOT_TIMEOUT_MS },
  );
  assert(start.code === 0, `flockctl start failed: ${start.stderr}`);
  await ctx.waitForDaemon();

  // ── Seed key, workspace, project ─────────────────────────────────────
  const keyId = await seedAiKey(ctx.daemonUrl);
  const ws = await createWorkspace(ctx.daemonUrl, "agents-ws", keyId);
  const proj = await createProject(
    ctx.daemonUrl,
    "agents-proj",
    ws.id,
    keyId,
  );

  // Sanity: the daemon scaffolded .flockctl/ on both sides. The migrate
  // command itself doesn't require this (only `agents show` does), but
  // confirming it here keeps the test's assumptions honest.
  assert(
    await pathExists(ctx, `${ws.path}/.flockctl`),
    `workspace ${ws.path} should have .flockctl/ scaffold after create`,
  );
  assert(
    await pathExists(ctx, `${proj.path}/.flockctl`),
    `project ${proj.path} should have .flockctl/ scaffold after create`,
  );

  // The daemon pre-creates an empty .flockctl/AGENTS.md on both sides.
  // Clear them so the plan has a real "write (0 -> N bytes)" entry
  // instead of short-circuiting to a "already matches" noop for every
  // candidate write. This mirrors the state a real repo would be in
  // right before the first migration — the legacy reconciler owned
  // AGENTS.md, the per-layer private sources weren't a thing yet.
  await ctx.exec(
    [
      "sh",
      "-c",
      `rm -f ${JSON.stringify(`${proj.path}/.flockctl/AGENTS.md`)} ${JSON.stringify(`${ws.path}/.flockctl/AGENTS.md`)}`,
    ],
    { raw: true, timeoutMs: 5_000 },
  );

  // ── Seed the legacy reconcile markers in the PROJECT's root AGENTS.md.
  //    This is the bit `planMigration` will split back into per-layer
  //    sources: the project block lands in <project>/.flockctl/AGENTS.md,
  //    the workspace block lands in <workspace>/.flockctl/AGENTS.md.
  const workspaceBody = "# Workspace guidance\n\nUse Drizzle, not raw SQL.";
  const projectBody =
    "# Project guidance\n\nBe concise. Prefer Hono handlers over Express.";
  await writeFileInContainer(
    ctx,
    `${proj.path}/AGENTS.md`,
    legacyAgentsMd(workspaceBody, projectBody),
  );

  // Snapshot the project tree so the dry-run invariance check has a
  // ground-truth to compare against.
  const hashBeforeDryRun = await treeHashInContainer(ctx, proj.path);
  // And the workspace tree — dry-run must not touch the workspace side
  // either (the plan proposes writing <ws>/.flockctl/AGENTS.md but must
  // not execute it).
  const wsHashBeforeDryRun = await treeHashInContainer(ctx, ws.path);

  // ── Step 4: dry-run. ───────────────────────────────────────────────
  const dry = await ctx.exec(
    ["agents", "migrate", proj.path, "--dry-run"],
    { timeoutMs: 20_000 },
  );
  assert(
    dry.code === 0,
    `agents migrate --dry-run exit ${dry.code}; stderr=${dry.stderr}; stdout=${dry.stdout}`,
  );
  assert(
    /Migration plan:/.test(dry.stdout),
    `dry-run: expected "Migration plan:" header, got:\n${dry.stdout}`,
  );
  // The plan proposes two writes (project-private + workspace-private)
  // plus a delete of the root AGENTS.md — the legacy file.
  assert(
    /- write:\s+.+\.flockctl\/AGENTS\.md/.test(dry.stdout),
    `dry-run: expected a "write:" line for a .flockctl/AGENTS.md path, got:\n${dry.stdout}`,
  );
  assert(
    /- delete:\s+.+\/AGENTS\.md/.test(dry.stdout),
    `dry-run: expected a "delete:" line for the root AGENTS.md, got:\n${dry.stdout}`,
  );
  assert(
    /dry run — rerun with --apply/i.test(dry.stdout),
    `dry-run: expected dry-run banner, got:\n${dry.stdout}`,
  );
  // Must NOT have invoked apply.
  assert(
    !/^Applied\./m.test(dry.stdout),
    `dry-run: should not print "Applied.", got:\n${dry.stdout}`,
  );

  // Invariance: neither side's tree changed.
  const hashAfterDryRun = await treeHashInContainer(ctx, proj.path);
  const wsHashAfterDryRun = await treeHashInContainer(ctx, ws.path);
  assert(
    hashBeforeDryRun === hashAfterDryRun,
    `dry-run modified the project tree (hash drifted from ${hashBeforeDryRun} to ${hashAfterDryRun})`,
  );
  assert(
    wsHashBeforeDryRun === wsHashAfterDryRun,
    `dry-run modified the workspace tree (hash drifted from ${wsHashBeforeDryRun} to ${wsHashAfterDryRun})`,
  );

  // Secondary cross-check: the hash we compute on the host from the
  // legacy body matches what we read back from the container, which rules
  // out a silent encoding transform on the file roundtrip.
  const rootBody = await readFileInContainer(ctx, `${proj.path}/AGENTS.md`);
  assert(
    rootBody !== null,
    `dry-run: root AGENTS.md must still exist at ${proj.path}/AGENTS.md`,
  );
  const expectedBody = legacyAgentsMd(workspaceBody, projectBody);
  assert(
    createHash("sha256").update(rootBody).digest("hex") ===
      createHash("sha256").update(expectedBody).digest("hex"),
    `dry-run: root AGENTS.md content drifted`,
  );

  // ── Step 5: apply. ──────────────────────────────────────────────────
  const apply = await ctx.exec(
    ["agents", "migrate", proj.path, "--apply"],
    { timeoutMs: 20_000 },
  );
  assert(
    apply.code === 0,
    `agents migrate --apply exit ${apply.code}; stderr=${apply.stderr}; stdout=${apply.stdout}`,
  );
  assert(
    /^Applied\.$/m.test(apply.stdout),
    `apply: expected "Applied." line, got:\n${apply.stdout}`,
  );
  assert(
    !/dry run/i.test(apply.stdout),
    `apply: must NOT print dry-run banner, got:\n${apply.stdout}`,
  );

  // Post-apply filesystem invariants.
  assert(
    !(await pathExists(ctx, `${proj.path}/AGENTS.md`)),
    `apply: root ${proj.path}/AGENTS.md should be gone`,
  );
  const projPrivate = await readFileInContainer(
    ctx,
    `${proj.path}/.flockctl/AGENTS.md`,
  );
  assert(
    projPrivate === projectBody,
    `apply: project private source mismatch.\nexpected: ${JSON.stringify(projectBody)}\ngot:      ${JSON.stringify(projPrivate)}`,
  );
  const wsPrivate = await readFileInContainer(
    ctx,
    `${ws.path}/.flockctl/AGENTS.md`,
  );
  assert(
    wsPrivate === workspaceBody,
    `apply: workspace private source mismatch.\nexpected: ${JSON.stringify(workspaceBody)}\ngot:      ${JSON.stringify(wsPrivate)}`,
  );

  // ── Step 6: re-apply is a no-op. ────────────────────────────────────
  const reapply = await ctx.exec(
    ["agents", "migrate", proj.path, "--apply"],
    { timeoutMs: 20_000 },
  );
  assert(
    reapply.code === 0,
    `agents migrate --apply (second run) exit ${reapply.code}; stderr=${reapply.stderr}; stdout=${reapply.stdout}`,
  );
  assert(
    /noop/i.test(reapply.stdout),
    `second apply: expected a "noop" line in the plan, got:\n${reapply.stdout}`,
  );
  assert(
    /nothing to migrate/i.test(reapply.stdout),
    `second apply: expected "nothing to migrate" reason, got:\n${reapply.stdout}`,
  );
  // Second apply hits the "noop-only plan" branch, which still prints
  // "Applied." (applyMigration happily walks a plan whose actions are
  // all noops). We don't assert on that — what matters is that the tree
  // stays byte-identical.
  const hashAfterReapply = await treeHashInContainer(ctx, proj.path);
  // Compare against a fresh post-apply snapshot rather than the pre-
  // apply hash — the tree obviously changed during apply.
  const hashPostFirstApply = await treeHashInContainer(ctx, proj.path);
  assert(
    hashAfterReapply === hashPostFirstApply,
    `second apply modified the project tree (hash ${hashPostFirstApply} -> ${hashAfterReapply})`,
  );

  // ── Step 7: `agents show --effective <project>`. ───────────────────
  // `--effective` is the default; pass it explicitly so we exercise the
  // flag-present branch in commander (and match the brief literally).
  // `.flockctl/` exists on both sides now (the daemon scaffolded it and
  // apply wrote into it), so assertKnownFlockctlPath is satisfied.
  const show = await ctx.exec(
    ["agents", "show", "--effective", proj.path],
    { timeoutMs: 15_000 },
  );
  assert(
    show.code === 0,
    `agents show --effective exit ${show.code}; stderr=${show.stderr}; stdout=${show.stdout}`,
  );
  assert(
    show.stdout.includes(projectBody),
    `agents show: expected project body in output, got:\n${show.stdout}`,
  );
  assert(
    show.stdout.includes(workspaceBody),
    `agents show: expected workspace body in output (loader merges layers), got:\n${show.stdout}`,
  );
  // Loader output is pipe-friendly — no ANSI.
  // eslint-disable-next-line no-control-regex
  assert(
    !/\u001b\[/.test(show.stdout),
    `agents show: output must not contain ANSI escapes`,
  );

  // ── Step 8: `agents show --layers <project>` — exercises the --layers
  //    JSON-summary branch (stdout is a parseable object, not the merged
  //    string). Kept after --effective so the fixture state is identical.
  const layers = await ctx.exec(
    ["agents", "show", proj.path, "--layers"],
    { timeoutMs: 15_000 },
  );
  assert(
    layers.code === 0,
    `agents show --layers exit ${layers.code}; stderr=${layers.stderr}`,
  );
  const layersJson = JSON.parse(layers.stdout) as {
    layers: Array<{ layer: string; path: string; bytes: number; truncated: boolean }>;
    totalBytes: number;
    truncatedLayers: string[];
  };
  assert(
    Array.isArray(layersJson.layers),
    `agents show --layers: expected .layers array, got:\n${layers.stdout}`,
  );
  assert(
    typeof layersJson.totalBytes === "number" && layersJson.totalBytes > 0,
    `agents show --layers: totalBytes must be a positive number, got ${layersJson.totalBytes}`,
  );
  // The summary must not leak the merged body.
  assert(
    !layers.stdout.includes(projectBody),
    `agents show --layers: must not leak project body, got:\n${layers.stdout}`,
  );

  // ── Step 9: error paths — each hits a distinct branch of
  //    assertKnownFlockctlPath.
  // 9a. Path that doesn't exist on disk → "Path not found".
  const missing = "/flockctl-home/definitely-not-here";
  const showMissing = await ctx.exec(
    ["agents", "show", missing],
    { timeoutMs: 15_000 },
  );
  assert(
    showMissing.code !== 0,
    `agents show <missing>: expected non-zero exit, got ${showMissing.code}`,
  );
  assert(
    /Error:.*Path not found/i.test(showMissing.stderr),
    `agents show <missing>: expected "Path not found", got:\n${showMissing.stderr}`,
  );

  // 9b. Path exists but has no `.flockctl/` scaffold.
  const bogus = "/flockctl-home/not-a-project";
  await ctx.exec(["sh", "-c", `mkdir -p ${bogus}`], {
    raw: true,
    timeoutMs: 5_000,
  });
  const showUnknown = await ctx.exec(
    ["agents", "show", bogus],
    { timeoutMs: 15_000 },
  );
  assert(
    showUnknown.code !== 0,
    `agents show <unknown>: expected non-zero exit, got ${showUnknown.code}`,
  );
  assert(
    /Error:.*not a known flockctl project/i.test(showUnknown.stderr),
    `agents show <unknown>: expected "not a known flockctl project" in stderr, got:\n${showUnknown.stderr}`,
  );

  // 9c. Path exists and has a `.flockctl` entry, but it's a regular
  //    file, not a directory → "(.flockctl exists but is not a directory)".
  const weird = "/flockctl-home/flockctl-is-a-file";
  await ctx.exec(
    [
      "sh",
      "-c",
      `rm -rf ${JSON.stringify(weird)}; mkdir -p ${JSON.stringify(weird)}; : > ${JSON.stringify(`${weird}/.flockctl`)}`,
    ],
    { raw: true, timeoutMs: 5_000 },
  );
  const showWeird = await ctx.exec(
    ["agents", "show", weird],
    { timeoutMs: 15_000 },
  );
  assert(
    showWeird.code !== 0,
    `agents show <file-flockctl>: expected non-zero exit, got ${showWeird.code}`,
  );
  assert(
    /\.flockctl exists but is not a directory/i.test(showWeird.stderr),
    `agents show <file-flockctl>: expected "is not a directory" stderr, got:\n${showWeird.stderr}`,
  );

  // 9d. <path> is a file, not a directory → "not a directory".
  const filePath = "/flockctl-home/just-a-file";
  await ctx.exec(
    ["sh", "-c", `: > ${JSON.stringify(filePath)}`],
    { raw: true, timeoutMs: 5_000 },
  );
  const showFile = await ctx.exec(
    ["agents", "show", filePath],
    { timeoutMs: 15_000 },
  );
  assert(
    showFile.code !== 0,
    `agents show <file>: expected non-zero exit, got ${showFile.code}`,
  );
  assert(
    /is not a directory/i.test(showFile.stderr),
    `agents show <file>: expected "is not a directory" stderr, got:\n${showFile.stderr}`,
  );

  // ── Step 10: blocked migrate — a manually-edited root AGENTS.md with no
  //    AUTO-GENERATED marker. plan.blocked is true, --force is absent, so
  //    the action exits 1 after printing the plan. Exercises the
  //    `plan.blocked && !opts.force` branch. Uses a standalone project so
  //    `tryResolveWorkspacePathForProject` also hits the
  //    `workspaceId === null` branch inline.
  const standalone = await createProjectStandalone(ctx.daemonUrl, "agents-solo", keyId);
  await writeFileInContainer(
    ctx,
    `${standalone.path}/AGENTS.md`,
    "# Hand-rolled rules\n\nNo AUTO-GENERATED marker.\n",
  );
  const blocked = await ctx.exec(
    ["agents", "migrate", standalone.path],
    { timeoutMs: 15_000 },
  );
  assert(
    blocked.code !== 0,
    `blocked migrate: expected non-zero exit, got ${blocked.code}; stdout=${blocked.stdout}`,
  );
  assert(
    /BLOCKED/i.test(blocked.stdout),
    `blocked migrate: expected BLOCKED banner in stdout, got:\n${blocked.stdout}`,
  );
  assert(
    /manual edit detected/i.test(blocked.stdout),
    `blocked migrate: expected "manual edit detected" warning, got:\n${blocked.stdout}`,
  );

  // ── Step 11: `--workspace` kind migrate. Seed a fresh legacy-style
  //    workspace AGENTS.md at the workspace root and migrate it as a
  //    workspace. Exercises the `kind === "workspace"` branch in the
  //    action (workspacePath is explicitly undefined — no daemon lookup).
  //    The apply path writes <ws>/.flockctl/AGENTS.md from the workspace
  //    block. The workspace's existing .flockctl/AGENTS.md (from Step 5)
  //    is removed first so the plan emits a "write" not a "noop".
  await ctx.exec(
    [
      "sh",
      "-c",
      `rm -f ${JSON.stringify(`${ws.path}/.flockctl/AGENTS.md`)}`,
    ],
    { raw: true, timeoutMs: 5_000 },
  );
  const wsBody2 = "# Refreshed workspace guidance\n\nPrefer zod schemas.";
  await writeFileInContainer(
    ctx,
    `${ws.path}/AGENTS.md`,
    // Workspace-kind legacy files don't have a project block.
    "<!-- AUTO-GENERATED by flockctl — do not edit this file directly.\n" +
      "     CLAUDE.md in this directory is a symlink to this file. -->\n\n" +
      `<!-- BEGIN workspace AGENTS.md (from <workspace>/.flockctl/AGENTS.md) -->\n` +
      `${wsBody2}\n` +
      `<!-- END workspace AGENTS.md -->\n`,
  );
  const wsMigrate = await ctx.exec(
    ["agents", "migrate", ws.path, "--workspace", "--apply"],
    { timeoutMs: 20_000 },
  );
  assert(
    wsMigrate.code === 0,
    `--workspace migrate exit ${wsMigrate.code}; stderr=${wsMigrate.stderr}; stdout=${wsMigrate.stdout}`,
  );
  assert(
    /^Applied\.$/m.test(wsMigrate.stdout),
    `--workspace migrate: expected "Applied." line, got:\n${wsMigrate.stdout}`,
  );
  assert(
    !(await pathExists(ctx, `${ws.path}/AGENTS.md`)),
    `--workspace migrate: root ${ws.path}/AGENTS.md should be gone`,
  );
  const wsPrivate2 = await readFileInContainer(
    ctx,
    `${ws.path}/.flockctl/AGENTS.md`,
  );
  assert(
    wsPrivate2 === wsBody2,
    `--workspace migrate: workspace private source mismatch.\nexpected: ${JSON.stringify(wsBody2)}\ngot:      ${JSON.stringify(wsPrivate2)}`,
  );

  // ── Step 12: workspace deleted underneath a legacy project AGENTS.md →
  //    `tryResolveWorkspacePathForProject` catches the /workspaces/:id
  //    404 and returns undefined. planMigration then emits a warning
  //    about the skipped workspace-private write instead of throwing.
  //    Uses a fresh workspace + project pair so we don't disturb the
  //    migration state already asserted above.
  const ws2 = await createWorkspace(ctx.daemonUrl, "agents-ws-doomed", keyId);
  const proj2 = await createProject(
    ctx.daemonUrl,
    "agents-proj-doomed",
    ws2.id,
    keyId,
  );
  // Clear the scaffolded file so the plan has a real write entry.
  await ctx.exec(
    [
      "sh",
      "-c",
      `rm -f ${JSON.stringify(`${proj2.path}/.flockctl/AGENTS.md`)}`,
    ],
    { raw: true, timeoutMs: 5_000 },
  );
  await writeFileInContainer(
    ctx,
    `${proj2.path}/AGENTS.md`,
    legacyAgentsMd("WS-BODY", "PROJ-BODY"),
  );
  // Delete the workspace row (the project row keeps its stale
  // workspaceId FK) so the GET /workspaces/:id inside
  // tryResolveWorkspacePathForProject throws.
  const delWs = await fetch(`${ctx.daemonUrl}/workspaces/${ws2.id}`, {
    method: "DELETE",
  });
  assert(
    delWs.ok || delWs.status === 204,
    `DELETE /workspaces/${ws2.id} failed: ${delWs.status}`,
  );
  const orphanMigrate = await ctx.exec(
    ["agents", "migrate", proj2.path, "--dry-run"],
    { timeoutMs: 15_000 },
  );
  assert(
    orphanMigrate.code === 0,
    `orphan migrate exit ${orphanMigrate.code}; stderr=${orphanMigrate.stderr}`,
  );
  assert(
    /workspace block present .* no workspacePath supplied/i.test(orphanMigrate.stdout),
    `orphan migrate: expected workspace-skipped warning, got:\n${orphanMigrate.stdout}`,
  );
});

console.log("agents: ok");
