import { test, expect } from "@playwright/test";
import { createProject, uniq } from "./_helpers";

/**
 * E2E for the FileTree filter input.
 *
 * The seeded e2e backend uses `/tmp/<name>` project paths with no real
 * files in them, so the tree itself renders the empty placeholder.
 * That's still enough surface for the filter contract:
 *
 *   1. The input is rendered above the tree (visible regardless of
 *      whether the tree body is loading / empty / populated).
 *   2. Typing into the input updates its value and the (debounced)
 *      `searchTerm` flow.
 *   3. The clear button restores the empty value.
 *
 * The filter behaviour against a populated tree (matches highlight,
 * non-matches hide, ancestors auto-expand) is owned by the unit test
 * — react-arborist's matcher is the library's own concern, and we
 * don't want this spec coupled to a specific repo fixture's layout.
 *
 * Visual baseline lives at
 * `ui/e2e/__screenshots__/tree-with-filter.png`. The snapshot itself
 * is generated by running:
 *   npm run e2e:update -- code-mode-filter
 */

test.describe("code-mode file-tree filter", () => {
  test("renders the filter input above the tree", async ({
    page,
    request,
  }) => {
    const proj = await createProject(request, uniq("filter"));
    await page.goto(`/projects/${proj.id}?tab=code`);

    const root = page.getByTestId("code-mode-root");
    test.skip(
      !(await root.isVisible().catch(() => false)),
      "CodeMode is not mounted on the project-detail page yet.",
    );

    const tree = page.getByTestId("file-tree-root");
    await expect(tree).toBeVisible();

    const filter = page.getByTestId("file-tree-filter");
    await expect(filter).toBeVisible();

    const input = page.getByTestId("file-tree-filter-input");
    await expect(input).toBeVisible();
    await expect(input).toHaveAttribute("aria-label", "Filter files");
  });

  test("typing updates the input value and the clear button toggles", async ({
    page,
    request,
  }) => {
    const proj = await createProject(request, uniq("filter-type"));
    await page.goto(`/projects/${proj.id}?tab=code`);

    const root = page.getByTestId("code-mode-root");
    test.skip(
      !(await root.isVisible().catch(() => false)),
      "CodeMode is not mounted on the project-detail page yet.",
    );

    const input = page.getByTestId("file-tree-filter-input");
    await expect(input).toBeVisible();

    // Initially the clear button is hidden — empty input.
    await expect(page.getByTestId("file-tree-filter-clear")).toHaveCount(0);

    await input.fill("readme");
    await expect(input).toHaveValue("readme");

    // Clear button appears.
    const clear = page.getByTestId("file-tree-filter-clear");
    await expect(clear).toBeVisible();

    // Wait past the 150ms debounce so the searchTerm has actually been
    // forwarded — there's no observable side-effect on an empty tree,
    // but this exercises the same code path the populated case uses.
    await page.waitForTimeout(200);

    await clear.click();
    await expect(input).toHaveValue("");
    await expect(page.getByTestId("file-tree-filter-clear")).toHaveCount(0);
  });

  test("tree-with-filter visual baseline", async ({ page, request }) => {
    const proj = await createProject(request, uniq("filter-snap"));
    await page.goto(`/projects/${proj.id}?tab=code`);

    const root = page.getByTestId("code-mode-root");
    test.skip(
      !(await root.isVisible().catch(() => false)),
      "CodeMode is not mounted on the project-detail page yet.",
    );

    const tree = page.getByTestId("file-tree-root");
    await expect(tree).toBeVisible();

    // Freeze animations so the snapshot doesn't drift on a half-played
    // hover / focus-ring transition.
    await page.addStyleTag({
      content:
        "*, *::before, *::after { animation-duration: 0s !important; transition-duration: 0s !important; }",
    });

    await expect(tree).toHaveScreenshot("tree-with-filter.png", {
      maxDiffPixelRatio: 0.02,
    });
  });
});

/**
 * Gitignore show/hide toggle — separate describe block so it can be
 * filtered ("npm run test:e2e -- -g 'gitignore toggle'") without
 * dragging the search-input suite along.
 *
 * Pinned contracts:
 *
 *   1. Default visibility is "shown" (operator who has never touched
 *      the toggle sees every file). This matches the localStorage
 *      default applied by `ProjectCodeMode`.
 *   2. Clicking flips the `data-show-ignored` attribute and persists
 *      the new value to `localStorage["code-mode.show-ignored"]`.
 *   3. A reload restores the persisted value — the operator's choice
 *      survives navigation.
 *
 * The seeded `/tmp/<name>` project paths are empty on the e2e backend,
 * so the actual tree-content diff between shown vs hidden is
 * exercised by the unit test (`file-tree-gitignore.test.tsx`). Here we
 * pin the header-level state machine + persistence + the visual
 * baselines for the toggle's two icon states.
 */
test.describe("code-mode gitignore toggle", () => {
  test("default state reads localStorage default (true) and persists flips across reload", async ({
    page,
    request,
  }) => {
    const proj = await createProject(request, uniq("gitignore-toggle"));
    await page.goto(`/projects/${proj.id}?tab=code`);

    const root = page.getByTestId("code-mode-root");
    test.skip(
      !(await root.isVisible().catch(() => false)),
      "CodeMode is not mounted on the project-detail page yet.",
    );

    // Wipe any leftover persisted value so the first assertion is the
    // genuine "operator has never touched the toggle" baseline.
    // localStorage is per-origin, so a previous test run could have
    // left a stale "false" behind.
    await page.evaluate(() =>
      window.localStorage.removeItem("code-mode.show-ignored"),
    );
    await page.reload();
    await page.getByTestId("project-detail-tab-code").click();

    const toggle = page.getByTestId("code-mode-show-ignored-toggle");
    await expect(toggle).toBeVisible();
    await expect(toggle).toHaveAttribute("data-show-ignored", "true");
    await expect(toggle).toHaveAttribute("aria-pressed", "true");

    // Click → flips to hidden. The aria-label flips with it so screen
    // readers describe the *next* action ("Show gitignored files").
    await toggle.click();
    await expect(toggle).toHaveAttribute("data-show-ignored", "false");
    await expect(toggle).toHaveAttribute("aria-pressed", "false");
    await expect(toggle).toHaveAttribute(
      "aria-label",
      "Show gitignored files",
    );

    const stored = await page.evaluate(() =>
      window.localStorage.getItem("code-mode.show-ignored"),
    );
    expect(stored).toBe("false");

    // Reload — the persisted "false" must come back through the
    // `useState(readShowIgnored)` initialiser.
    await page.reload();
    await page.getByTestId("project-detail-tab-code").click();
    const toggleAfterReload = page.getByTestId(
      "code-mode-show-ignored-toggle",
    );
    await expect(toggleAfterReload).toHaveAttribute(
      "data-show-ignored",
      "false",
    );

    // Click again → restores "shown" and overwrites localStorage.
    await toggleAfterReload.click();
    await expect(toggleAfterReload).toHaveAttribute(
      "data-show-ignored",
      "true",
    );
    const storedAfterFlip = await page.evaluate(() =>
      window.localStorage.getItem("code-mode.show-ignored"),
    );
    expect(storedAfterFlip).toBe("true");
  });

  test("visual baselines: ignored-shown-faded vs ignored-hidden", async ({
    page,
    request,
  }) => {
    const proj = await createProject(request, uniq("gitignore-vis"));
    await page.goto(`/projects/${proj.id}?tab=code`);

    const root = page.getByTestId("code-mode-root");
    test.skip(
      !(await root.isVisible().catch(() => false)),
      "CodeMode is not mounted on the project-detail page yet.",
    );

    // Force the "shown" baseline so the snapshot is reproducible
    // regardless of what previous specs persisted.
    await page.evaluate(() =>
      window.localStorage.setItem("code-mode.show-ignored", "true"),
    );
    await page.reload();
    await page.getByTestId("project-detail-tab-code").click();

    // Freeze animations so the snapshot doesn't drift on a half-played
    // hover / focus-ring transition.
    await page.addStyleTag({
      content:
        "*, *::before, *::after { animation-duration: 0s !important; transition-duration: 0s !important; }",
    });

    const filesPanel = page.getByTestId("code-mode-files-panel");
    await expect(filesPanel).toBeVisible();
    await expect(
      page.getByTestId("code-mode-show-ignored-toggle"),
    ).toHaveAttribute("data-show-ignored", "true");

    // Baseline #1 — ignored entries are shown (faded). On a populated
    // project the dimmed rows would be visible inline; on the empty
    // seed the differentiator is the toggle's `Eye` glyph in the
    // header strip.
    await expect(filesPanel).toHaveScreenshot(
      "tree-ignored-shown-faded.png",
      { maxDiffPixelRatio: 0.02 },
    );

    // Flip to hidden and re-screenshot.
    await page.getByTestId("code-mode-show-ignored-toggle").click();
    await expect(
      page.getByTestId("code-mode-show-ignored-toggle"),
    ).toHaveAttribute("data-show-ignored", "false");

    // Baseline #2 — ignored entries are filtered out of the tree
    // data; the header carries the `EyeOff` glyph.
    await expect(filesPanel).toHaveScreenshot("tree-ignored-hidden.png", {
      maxDiffPixelRatio: 0.02,
    });
  });
});
